# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 100 # it will paginate after this number
language: 'id'

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: ''
# Website info
title: Panduan olshop Kapiten
description: Kumpulan panduan dan tips untuk membangun bisnis jual-beli online

## STATICMAN
# Staticman comments (see staticman.yml for configuration).
# Name of repository, for use with Staticman
# repository: "galliani/raptor" # SET IN environment_variables.rb
staticman:
  branch: "master"

cover: /assets/images/blog-cover.jpg
logo: /assets/images/logo-only-white.png
logo_dark: /assets/images/kapiten-favicon.png
favicon: /assets/images/kapiten-favicon.png

collections:
  posts:
    output: true
    permalink: /panduan-olshop/:title
  authors:
    output: true
    permalink: /panduan-olshop/author/:author

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "authors"
    values:
      layout: author

# Social info
navigation: True # show the navbar links
subscribers: True # you need to connect an external service for this to work,

# Permalinks
# permalink: /:title
# permalink: /author/:author
# permalink: /tag/:tag

# gems and other configs
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

feed:
  path: feed.xml

exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
  - netlify.toml