# The following redirect is intended for use with most SPA's that handles routing internally.
[[redirects]]
  from = "/"
  to = "/panduan-olshop"
  status = 200
  force = true # Ensure that we always redirect